# Generated by Django 5.2 on 2025-06-11 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_checkboxitem_note_alter_numbereditem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcheckboxes', to='notas.checkboxitem'),
        ),
    ]
