# Generated by Django 5.2 on 2025-06-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_checkboxitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
