# Generated by Django 5.2 on 2025-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checkbox_images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
    ]
